### ISSUE TITLE
Quick start template fails to deploy when the CloudFormation Stack name is long  

### ISSUE THREAD

**Issue by andrew-j-roberts** [SolaceLabs/solace-aws-service-integration#11]
Deploying the quick start template fails when the CloudFormation stack name is long  

**In the parent stack, it throws the error message:**
"The following resource(s) failed to create: [SecurityGroupStack, RoleStack]. 

**When you follow the error to the ApiGateway nested stack, the stack fails to build the ApiProxyRole component with error message:**
"1 validation error detected: Value '<role-name-removed-intentionally>' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError...)

**Comment by PhilippeKhalife** [comment]
Fixed with latest updates
