### ISSUE TITLE
TemplateURL is not a valid S3 URL

### ISSUE THREAD

**Issue by mkaleru** [SolaceLabs/solace-aws-service-integration#7]
The new AWS Stack interface breaks the template URL because of "+" sign (api_proxy+vmr.template), though it works in the old interface.
![aws-stack-issue](https://user-images.githubusercontent.com/7130051/50905680-fb3e1100-13e8-11e9-9636-dcd4e2d26c5b.png)

**Comment by KenBarr** [comment]
Fixed and verified with commit https://github.com/SolaceLabs/solace-aws-service-integration/commit/8b39171eb4f27f35776ad91bb27c7027f8271c29
