### ISSUE TITLE
S3 bucket regionality differences cause resource access issues

### ISSUE THREAD

**Issue by KenBarr** [SolaceLabs/solace-aws-service-integration#9]
Originally tested in us-east-1 which is unique in how S3 URLs are defined:

docs say this:
In a path-style URL, the bucket name is not part of the domain. For example:
Region-specific endpoint, http://s3-aws-region.amazonaws.com/bucket
US East (N. Virginia) Region endpoint, http://s3.amazonaws.com/bucket

Need to take this into account.

**Comment by PhilippeKhalife** [comment]
Fixed with latest updates, options available for non default region.
